### ISSUE TITLE
Using names that are longer than a word

### ISSUE THREAD

**Issue by rossgardt** [RichardLitt/remark-lint-appropriate-heading#3]
I receive warning when using a folder name that is using underscores.

E.g., when the folder name is `android_emulator` and the title is `Android Emulator` - I get an error.

How can I solve this?

Best,
Benji

**Comment by barraq** [comment]
https://github.com/RichardLitt/remark-lint-appropriate-heading/pull/4

**Comment by RichardLitt** [comment]
I think this has been solved now! @rossgardt What do you think?

**Comment by rossgardt** [comment]
Looks fine! 👍
